In [1]:
import numpy
from scipy import sparse
import matplotlib.pyplot as plt 
import pandas
import mglearn

from sklearn.datasets import load_iris

In [4]:
def printResult(*args):
    argsLen = len(args)
    if (argsLen) == 1:
        print("Results\n{}".format(args[0]));
    else:
        for i in range(0,argsLen,2):
            if ((i+1) == argsLen): break;
            print("{}:\n{}\n".format(args[i],args[i+1]));



In [54]:
A = numpy.array([[1,2],[3,4]]);
X = numpy.eye(6);
Xs = sparse.csr_matrix(X);
printResult('X',X,'Xs',Xs)

X:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Xs:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0



In [59]:
D = numpy.ones(4)
row_indices = numpy.arange(4);
col_indices = numpy.arange(4);
eye_coo = sparse.coo_matrix((D,(row_indices,col_indices)));
printResult(eye_coo)

Results
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [65]:
x = numpy.linspace(0,10);
y = numpy.sin(x);
# plt.plot(x,y,'-x');

In [69]:
data = {"Name" : ["John", "Anna", "Peter", "Linda"],
        "Location": ["New York", "Paris", "Berlin", "London"],
        "Age" :  [24, 13, 53, 33]};

dataF = pandas.DataFrame(data);
printResult(dataF);

Results
    Name  Location  Age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33


In [8]:
iris_dataset = load_iris()
iris_dataset['DESCR'][:193]

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, pre'